### ISSUE TITLE
Suggestion: debouncing based on event sources

### ISSUE THREAD

**Issue by thomashoneyman** [citizennet/purescript-halogen-select#34]
@dariooddenino has a great gist of using event sources for debouncing in search:
https://gist.github.com/dariooddenino/452827d9d95c8fc3b651c009d2b9b2ea

here it is in practice:
https://gist.github.com/dariooddenino/eb0fc7fd863ae37d8ca9962b7ea824dc

this is nice because the debouncer isn't being kept in state, so we don't end up causing unnecessary re-renders, and it's a bit nicer interface to work with.

**Comment by thomashoneyman** [comment]
I've actually changed my mind on this one. This debouncer uses the component's query type as part of `State`, which would require changing the type signature of our `State` type to incorporate extra type parameters. I'm loath to do this given how type parameters are infectious / scary and this is a fairly minor improvement.

I haven't properly explored it, but it's possible that storing the debouncer in a `Ref` instead of directly in state would allow modification without re-rendering. We don't need the information for rendering anyway. I'll need to check with Gary or Nate or someone more knowledgeable on that one, though.

**Comment by MonoidMusician** [comment]
I wonder if, by specializing it to your specific query, you could avoid the type variables. Actually, what if you just hid them with a newtype:

```purescript
data QueryF o item a = ...
  | SendSearch a

newtype AnyQueryF a = AnyQueryF (forall o item. QueryF o item a)

sendSearch :: forall a. a -> AnyQueryF a
sendSearch a = AnyQueryF (SendSearch a)

type DebounceTrigger = Utils.Debounced.DebounceTrigger AnyQueryF Aff
```

(then I think you need to use `hoist liftAff` to get the right `MonadAff m => HalogenM ... m ...`, but the types should work out from there 🤞💪)

**Comment by davezuch** [comment]
#35 moves debouncing from state to a ref
