### ISSUE TITLE
Update documentation site to reflect Halogen 5 changes

### ISSUE THREAD

**Issue by thomashoneyman** [citizennet/purescript-halogen-select#41]
#38 introduces lots of changes to Select, including a fix for #36. The component is now used a bit differently and the documentation site is horribly out of date. (As a side note: it would be nice if the docs site could be browsed at a particular tag; as it stands, it will only show the latest branch).

Some major changes that will need to happen:

1. The tutorials will all need to be rewritten
2. The `QueryF` documentation should be removed
3. We should introduce a short example of how to embed parent queries like the old-style Select for those who were relying on that behavior (some people used Select to directly hook in to parent state -- for example, using a selection change to update the page header)
4. We should add a description of the various ways to extend Select (when should you extend state? when should you extend the query algebra?)
5. We should describe some new best practices: exporting a spec + a default input for your component; handling messages output by the component but providing your own new message interface for your spec; etc.

**Comment by milesfrain** [comment]
Made some partial progress with this:
* Updated [template](https://github.com/milesfrain/purescript-halogen-template/tree/tooling) to halogen5
* Edited the [getting-started](https://github.com/milesfrain/purescript-halogen-select/commit/1e4ee236e2222b1be5cf4fe8d871f5916ef202d0) section and some of the dropdown tutorial

Editing the dropdown tutorial requires working backwards from the completed dropdown example, and this is more involved than I expected.

I think updating the remaining chapters of the purescript book would be a better use of time with my current understanding of the language. Might circle back to this task later.

I'm also hoping to consolidate some of the web framework templates. Basing this tutorial on a more widely used template might reduce maintenance effort.

**Comment by thomashoneyman** [comment]
Thanks for getting started on this, @milesfrain!

Now that [purescript-templates/halogen](https://github.com/purescript-templates/halogen) exists and after [reading the 'Featured Templates' discussion on Discourse](https://discourse.purescript.org/t/featured-templates/1188/8) I think it's sensible for the CitizenNet template to be archived and for the tutorial here to be based on the `purescript-templates` version. That's up to @davezuch, though.

I agree that editing the dropdown tutorial will be involved; the new version of Select is quite different from v1 and I rewrote both examples as part of that update. Thanks for getting started, though, and this is a nice reminder for me to update the relevant documentation on my side.

**Comment by JordanMartinez** [comment]
@thomashoneyman Not sure when you read through that Discourse thread, but Harry brought up some good points at the end of the thread. So, I'm not sure whether this is the best approach still.

**Comment by thomashoneyman** [comment]
With #53 in mind, I’ll move straight to updating the documentation specifically for the Hooks implementation. With that in mind I’m going to close this issue.
