### ISSUE TITLE
Follow Halogen? Use full type names in type signature

### ISSUE THREAD

**Issue by JordanMartinez** [citizennet/purescript-halogen-select#44]
Does this library's Halogen 5 version (e.g. `v5.0.0-rc.2`) intend to follow the spirit of slamdata/purescript-halogen#562?

As a bad example, `act` could become `action`. `act` by itself is already pretty clear, but a few more letters don't hurt, right?
As a better example, `ps` could become `slots`. Unless you learned Halogen 4, `ps` is unclear until you get a compiler error that indicates what goes there or you look at the source code.

Slightly related, but perhaps changing `st` to `stateRows`?

**Comment by thomashoneyman** [comment]
I'm happy to change the variables to `action`, `slots`, etc. 

I'm of the opinion that `st` is a common-enough abbreviation of "state" that I'll likely leave it as-is. I'm not sure `stateRows` or `extraState` communicates much more at the cost of quite a few characters. I _usually_ don't care about variable lengths except for when there are several type parameters and the line lengths get uncomfortably long; in this case I'd prefer the shorter term in lieu of something which communicates quite a bit better.

Want to make this update as part of #45?

**Comment by JordanMartinez** [comment]
> I'm of the opinion that st is a common-enough abbreviation of "state" that I'll likely leave it as-is. 

Having thought about this more, I think this is actually the better decision. Rather than using `stateRows`, I think the tutorial should explain what is meant by `st`: a way to extend the component's default state with additional labels and values.

> Want to make this update as part of #45?

Sure! (I'll get to that later today)
